package com.kyrodatatech.banking.domain.transaction.enums;

public enum TransactionStatus {
    SUBMITTED,
    VALIDATION_PASSED,
    VALIDATION_FAILED,
    SANCTIONS_CLEARED,
    SANCTIONS_BLOCKED,
    AML_CLEARED,
    AML_FLAGGED,
    PENDING_CHECKER,
    PENDING_L1,
    PENDING_L2,
    PENDING_FINAL_AUTHORIZATION,
    APPROVED,
    REJECTED,
    PROCESSING,
    PROCESSING_FAILED,
    COMPLETED,
    REVERSED,
    CANCELLED
}
